// <auto-generated />
namespace VS02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VS0001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VS0001));
        
        string IMigrationMetadata.Id
        {
            get { return "201803192048005_VS0001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
